/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/search": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Start Search
     * @description Запустить прогон. Ответ приходит сразу: результат забирается по GET /search/{run_id}.
     */
    post: operations["start_search_search_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/search/{run_id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Search
     * @description Состояние прогона: stage — текущий шаг, status='done' — выдача готова.
     */
    get: operations["get_search_search__run_id__get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/search/{run_id}/evidence": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Evidence
     * @description Признаки и публикации по годам для всех кандидатов прогона — для карты сигналов и графиков.
     */
    get: operations["get_evidence_search__run_id__evidence_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/runs": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Runs
     * @description Последние прогоны для списка в интерфейсе: идущий и готовые, свежие первыми.
     */
    get: operations["list_runs_runs_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/signal/{run_id}/{candidate_id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Signal
     * @description Карточка одного сигнала из выдачи прогона.
     */
    get: operations["get_signal_signal__run_id___candidate_id__get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/health": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Health
     * @description Готовность сервиса: модель и база. Полезно перед демонстрацией — сразу видно, что не поднято.
     */
    get: operations["health_health_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /**
     * CandidateEvidence
     * @description Всё измеренное по одному кандидату. Годовые ряды пустые, если статистика не успела.
     */
    CandidateEvidence: {
      /** Candidate Id */
      candidate_id: string
      /** Name */
      name: string
      /** Name Ru */
      name_ru?: string | null
      features: components["schemas"]["CandidateFeatures"]
      /** Pubs By Year */
      pubs_by_year?: {
        [key: string]: number
      }
      /** Patents By Year */
      patents_by_year?: {
        [key: string]: number
      } | null
      /** News By Year */
      news_by_year?: {
        [key: string]: number
      } | null
    }
    /**
     * CandidateFeatures
     * @description Признаки кандидата. Одинаково считаются для датасета и для открытого поиска.
     */
    CandidateFeatures: {
      /** Candidate Id */
      candidate_id: string
      /** Total Pubs */
      total_pubs?: number | null
      /**
       * Growth 3Y
       * @description среднегодовой рост публикаций за 3 года
       */
      growth_3y?: number | null
      /** First Seen Year */
      first_seen_year?: number | null
      /** Patents Total */
      patents_total?: number | null
      /** News Total */
      news_total?: number | null
      /** News To Science Ratio */
      news_to_science_ratio?: number | null
      /** Distinct Orgs */
      distinct_orgs?: number | null
      /** Distinct Sources */
      distinct_sources?: number | null
      /** Has Wikipedia */
      has_wikipedia?: boolean | null
      /** Has Standard */
      has_standard?: boolean | null
      /** Stage */
      stage?: ("research" | "prototype" | "product" | "mass") | null
      /**
       * Extra
       * @description прочие признаки ML
       */
      extra?: {
        [key: string]: number | null
      }
    }
    /**
     * Explanation
     * @description Один «ключевой предиктор» — вклад признака в решение модели.
     */
    Explanation: {
      /** Feature */
      feature: string
      /** Value */
      value?: number | string | null
      /**
       * Contribution
       * @description вклад SHAP: >0 — за сигнал, <0 — против
       */
      contribution: number
      /**
       * Text
       * @description по-русски: «Публикации растут на 60% в год»
       */
      text: string
    }
    /**
     * FilterDecision
     * @description Решение правил отсева по кандидату.
     */
    FilterDecision: {
      /** Candidate Id */
      candidate_id: string
      /** Name */
      name: string
      /** Excluded */
      excluded: boolean
      /**
       * Reason Code
       * @enum {string}
       */
      reason_code: "mature" | "hype" | "noise" | "no_research" | "ok"
      /**
       * Reason Text
       * @description по-русски, для интерфейса: «Зрелая технология: 45 000 публикаций, есть стандарт ISO»
       */
      reason_text: string
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][]
    }
    /**
     * Health
     * @description Что сейчас работает. Без модели поиск бессмысленен, без базы — просто не переживёт перезапуск.
     */
    Health: {
      /**
       * Status
       * @enum {string}
       */
      status: "ok" | "degraded"
      /** Llm Model */
      llm_model: string
      /** Llm Available */
      llm_available: boolean
      /** Database Available */
      database_available: boolean
      /** Active Runs */
      active_runs: string[]
      /**
       * Notes
       * @description что не готово, по-русски
       */
      notes?: string[]
    }
    /**
     * ModelCall
     * @description Запись в лог моделей (требование ТЗ).
     */
    ModelCall: {
      /**
       * Step
       * @description expand_query | extract_candidates | embeddings | score | make_card | translate ...
       */
      step: string
      /** Model */
      model: string
      /**
       * Provider
       * @description ollama | huggingface | local | gigachat | yandexgpt ...
       */
      provider: string
      /** Duration Ms */
      duration_ms: number
      /**
       * Ts
       * Format: date-time
       */
      ts?: string
    }
    /** RunEvidence */
    RunEvidence: {
      /** Run Id */
      run_id: string
      /** Candidates */
      candidates?: components["schemas"]["CandidateEvidence"][]
    }
    /**
     * RunLeader
     * @description Технология из начала выдачи — чтобы в списке поисков было видно, что нашлось.
     */
    RunLeader: {
      /** Name */
      name: string
      /** Score */
      score: number
    }
    /**
     * RunSummary
     * @description Строка в списке прогонов: чтобы показать список, не нужно тянуть все карточки.
     */
    RunSummary: {
      /** Run Id */
      run_id: string
      /** Query */
      query: string
      /**
       * Status
       * @enum {string}
       */
      status: "running" | "done" | "error"
      /** Stage */
      stage: string
      /**
       * Started At
       * Format: date-time
       */
      started_at: string
      /** Duration S */
      duration_s: number | null
      /** Documents Processed */
      documents_processed: number
      /** Candidates Found */
      candidates_found: number
      /** Signals */
      signals: number
      /** Confident Signals */
      confident_signals: number
      /**
       * Leaders
       * @default []
       */
      leaders: components["schemas"]["RunLeader"][]
    }
    /** ScoredCandidate */
    ScoredCandidate: {
      /** Candidate Id */
      candidate_id: string
      /** Name */
      name: string
      /** Score */
      score: number
      /** Top Reasons */
      top_reasons?: components["schemas"]["Explanation"][]
    }
    /**
     * SearchRequest
     * @description Свободный запрос пользователя — тот же, что в CLI.
     */
    SearchRequest: {
      /** Query */
      query: string
    }
    /**
     * SearchResult
     * @description Результат прогона по запросу. Пока status='running', UI показывает stage как прогресс.
     */
    SearchResult: {
      /** Run Id */
      run_id: string
      /** Query */
      query: string
      /**
       * Status
       * @default running
       * @enum {string}
       */
      status: "running" | "done" | "error"
      /**
       * Stage
       * @default
       */
      stage: string
      /** Expanded Phrases */
      expanded_phrases?: string[]
      /**
       * Documents Processed
       * @default 0
       */
      documents_processed: number
      /**
       * Candidates Found
       * @default 0
       */
      candidates_found: number
      /**
       * Confident Signals
       * @description сколько сигналов со score > 0.75
       * @default 0
       */
      confident_signals: number
      /** Top */
      top?: components["schemas"]["SignalCard"][]
      /** Excluded */
      excluded?: components["schemas"]["FilterDecision"][]
      /**
       * Scored
       * @description все кандидаты после отсева с оценкой, по убыванию: «не нашли» vs «нашли, но низко»
       */
      scored?: components["schemas"]["ScoredCandidate"][]
      /** Model Calls */
      model_calls?: components["schemas"]["ModelCall"][]
      /**
       * Source Failures
       * @description источники, не ответившие за прогон: отказ виден в выдаче, а не только в логе
       */
      source_failures?: components["schemas"]["SourceFailure"][]
      /**
       * Started At
       * Format: date-time
       */
      started_at?: string
      /** Duration S */
      duration_s?: number | null
      /** Error */
      error?: string | null
    }
    /**
     * SignalCard
     * @description Карточка слабого сигнала в топ-15.
     */
    SignalCard: {
      /** Candidate Id */
      candidate_id: string
      /** Name */
      name: string
      /** Name Ru */
      name_ru?: string | null
      /** Score */
      score: number
      /** Description */
      description: string
      /** Advantage */
      advantage: string
      /** Case Example */
      case_example: string
      /** Why Weak Signal */
      why_weak_signal: string
      /** Top Reasons */
      top_reasons?: components["schemas"]["Explanation"][]
      /** Sources */
      sources: components["schemas"]["SourceRef"][]
      /**
       * Report Md
       * @description подробный отчёт, генерируется по клику
       */
      report_md?: string | null
    }
    /**
     * SourceFailure
     * @description Источник, который не ответил во время прогона.
     *
     *     Нужен, чтобы отказ было видно в результате, а не только в логе. Падение источника
     *     не валит прогон — это требование ТЗ, — но из-за этого мёртвый источник выглядит как
     *     обычная работа: карточек столько же, времени даже меньше (отказ приходит мгновенно).
     *     21.09 исчерпанный лимит OpenAlex дважды незаметно испортил замеры и увёл к неверным
     *     выводам, потому что понять это можно было только вычитыванием лога.
     */
    SourceFailure: {
      /** Source */
      source: string
      /**
       * Detail
       * @default
       */
      detail: string
      /**
       * Count
       * @default 1
       */
      count: number
    }
    /**
     * SourceRef
     * @description Источник в карточке сигнала — всё, что ТЗ требует показать.
     */
    SourceRef: {
      /** Document Id */
      document_id: string
      /**
       * Title
       * @description оригинальное название
       */
      title: string
      /** Url */
      url: string
      /** Published */
      published?: string | null
      source_type: components["schemas"]["SourceType"]
      /** Language */
      language: string
      trust: components["schemas"]["TrustLevel"]
      /**
       * Ru Summary
       * @description резюме на русском для зарубежных источников
       */
      ru_summary?: string | null
      /**
       * Summary Is Generated
       * @default false
       */
      summary_is_generated: boolean
      /**
       * Is Machine Translated
       * @default false
       */
      is_machine_translated: boolean
    }
    /**
     * SourceType
     * @description Тип источника. Показывается пользователю и влияет на уровень доверия.
     * @enum {string}
     */
    SourceType:
      | "paper"
      | "preprint"
      | "patent"
      | "news"
      | "report"
      | "gov"
      | "blog"
      | "social"
      | "press_release"
      | "other"
    /**
     * TrustLevel
     * @enum {string}
     */
    TrustLevel: "high" | "medium" | "low"
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
      /** Input */
      input?: unknown
      /** Context */
      ctx?: Record<string, never>
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  start_search_search_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["SearchRequest"]
      }
    }
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["SearchResult"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  get_search_search__run_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        run_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["SearchResult"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  get_evidence_search__run_id__evidence_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        run_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["RunEvidence"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  list_runs_runs_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["RunSummary"][]
        }
      }
    }
  }
  get_signal_signal__run_id___candidate_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        run_id: string
        candidate_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["SignalCard"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  health_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Health"]
        }
      }
    }
  }
}
